### ISSUE TITLE
i got error when npm start.

### ISSUE THREAD

**Issue by Mountains-and-rivers** [thorsten-stripe/ecommerce-gatsby-tutorial#4] opened 2019-04-17 08:03 UTC
```
error GraphQL Error Unknown field `allStripeSku` on type `Query`

  file: /Users/wangguilin/aliyunGit/ecommerce-gatsby-tutorial/src/components/Products/Skus.js

   1 | 
   2 |           query SkusForProduct {
>  3 |             skus: allStripeSku(
     |                   ^
   4 |               filter: { product: { id: { eq: "prod_EGl7ZnT96XrPf6" } } }
   5 |               sort: { fields: [price] }
   6 |             ) {
   7 |               edges {
   8 |                 node {
   9 |                   id
  10 |                   currency
  11 |                   price
  12 |                   attributes {
  13 |                     name


```

**Comment by DOSputin** [comment] 2019-07-28 05:58
duplicate of issue #3

**Comment by thorsten-stripe** [comment] 2019-07-29 19:52
I had a hardcoded product ID in the query, which would only work with my secret key, sorry about that!

I've fixed this and added a setup section to the README[0]. I've tested with a fresh Stripe account, so hopefully this should now work for you. Please reopen if you're still facing issues.

[0] https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial#setup

**Closed as completed by thorsten-stripe** 2019-07-29 19:52 UTC
